---
# Playbook to control the mockfog_network role

- name: Apply Network Definition
  hosts: all_nodes
  remote_user: ec2-user
  become: yes
  vars:
    network_interface: eth1
  roles:
    - mockfog_network
