- name: Include check_dependencies play
  include: "{{ playbook_dir }}/mockfog_application/tasks/check_dependencies.yml"

- name: Include check_variables play
  include: "{{ playbook_dir }}/mockfog_application/tasks/check_variables.yml"

- name: create agents dir
  file:
    path: "agent/"
    state: directory
    recurse: yes
    owner: ec2-user
    group: ec2-user

- name: Copy agent script
  copy:
    src: "{{ playbook_dir }}/mockfog_topology/files/agent.py"
    dest: agent/agent.py
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: create virtual env
  shell: "virtualenv .agent -p /usr/bin/python3"
  args:
    chdir: "agent/"
  become_user: ec2-user

- name: Install agent dependencies
  shell: ".agent/bin/pip install docker tcconfig"
  args:
    chdir: "agent/"
  become_user: ec2-user

- name: start agent
  shell: "sudo .mockfog_agent/bin/python mockfog_agent.py"