---
- import_tasks: deploy.yml
  tags: deploy

- import_tasks: collect.yml
  tags: collect

- import_tasks: check_dependencies.yml
  tags: check_dependencies

- import_tasks: deploy_agent.yml
  tags: deploy_agent

